[package]
name = "EMPACT"
version = "1.0.0"
description = "EMPACT: Environment and Maturity Project Assessment and Control Tool"
authors = ["Craig Haseler"]
license = "CC BY 4.0"
repository = "https://github.com/cahaseler/EMPACT"
default-run = "EMPACT"
edition = "2021"
rust-version = "1.60"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
tauri-build = { version = "=1.5.3", features = [] }

[dependencies]
serde_json = "=1.0.125"
serde = { version = "=1.0.208", features = ["derive"] }
tauri = { version = "=1.7.1", features = [] }

[features]
# this feature is used for production builds or when `devPath` points to the filesystem and the built-in dev server is disabled.
# If you use cargo directly instead of tauri's cli you can use this feature flag to switch between tauri's `dev` and `build` modes.
# DO NOT REMOVE!!
custom-protocol = [ "tauri/custom-protocol" ]
