name: release

on:
  push:
    branches:
      - "main"
  workflow_dispatch:

jobs:
  build_and_release:
    concurrency:
      group: ${{ github.workflow }}
    runs-on: windows-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
    outputs:
      version: ${{ steps.semantic-release.outputs.new_release_version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: main
          persist-credentials: false

      - name: Install Node.js 20 and Yarn
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'yarn'
          cache-dependency-path: 'yarn.lock'

      - name: Install Dependencies
        run: yarn install

      - name: Install Rust stable
        uses: dtolnay/rust-toolchain@stable

      - name: Rust Cache
        uses: swatinem/rust-cache@v2
        with:
          workspaces: "./src-tauri -> target"

      - name: Build Webapp
        run: |
          yarn sync-app
          yarn build-web
          yarn build-static

      - name: Switch to Node.js 14
        uses: actions/setup-node@v4
        with:
          node-version: 14

      - name: Semantic Release
        id: semantic-release
        uses: cycjimmy/semantic-release-action@v3
        with:
          extra_plugins: |
            @semantic-release/changelog
            @semantic-release/git
            @semantic-release/github
            @semantic-release/exec
            @google/semantic-release-replace-plugin@1.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN_SEMANTIC_RELEASE }}

  publish-docker-image:
    runs-on: ubuntu-latest
    needs: build_and_release
    permissions:
      contents: write
      issues: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: main
          persist-credentials: false

      - name: Install Node.js 18 and Yarn
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'yarn'
          cache-dependency-path: 'yarn.lock'

      - name: Install Dependencies
        run: |
          cd web
          yarn install

      - name: Build Webapp for Docker
        run: |
          cd web
          yarn build-linux

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker Image
        run: |
          cd web
          docker build --tag cahaseler/empact:latest --tag cahaseler/empact:${{ needs.build_and_release.outputs.version }} .
          docker push --all-tags cahaseler/empact
